services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - /srv/dev-disk-by-uuid-5bed169e-8d01-47f9-9b98-734d43be0482/Compose/home_assistant/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8123:8123 #optional
    restart: unless-stopped
    networks:
      - home-assistant_default
  ###############################################
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883 # MQTT
      - 9001:9001 # WebSocket MQTT
    volumes:
      - /srv/dev-disk-by-uuid-5bed169e-8d01-47f9-9b98-734d43be0482/Compose/home_assistant/mqtt/data:/mosquitto/data
      - /srv/dev-disk-by-uuid-5bed169e-8d01-47f9-9b98-734d43be0482/Compose/home_assistant/mqtt/config:/mosquitto/config
      - /srv/dev-disk-by-uuid-5bed169e-8d01-47f9-9b98-734d43be0482/Compose/home_assistant/mqtt/log:/mosquitto/log
    networks:
      - home-assistant_default
  ###########################
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: ghcr.io/koenkk/zigbee2mqtt
    restart: unless-stopped
    devices:
      - /dev/serial/by-id/usb-Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_16fad32d8fc2ef11a000c6138148b910-if00-port0:/dev/ttyUSB0
    volumes:
      - /srv/dev-disk-by-uuid-5bed169e-8d01-47f9-9b98-734d43be0482/Compose/home_assistant/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    environment:
      - TZ=Europe/Lisbon
    ports:
      - 8080:8080
    networks:
      - home-assistant_default
networks:
  home-assistant_default:
    external: true